### ISSUE TITLE
cannot load certificate from string

### ISSUE THREAD

**Issue by ttanner** [M2Crypto/M2Crypto#23]
X509.load_cert_string() fails to load perfectly fine PEM certificate (str).
Writing the certicate to a file and loading it using X509.load_cert works fine.

Python 2.7.9, MCrypt 0.22.3, openssl 1.0.1k, macports

```
Traceback (most recent call last):
    x509 = X509.load_cert_string(cert)
  File "$path/M2Crypto/X509.py", line 655, in load_cert_string
  File "$path/M2Crypto/X509.py", line 639, in load_cert_bio
M2Crypto.X509.X509Error: 140735113143056:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:703:Expecting: CERTIFICATE
```

**Comment by HanSooloo** [comment]
Had the same problem; turned out I was using/getting Unicode strings and M2Crypto didn't like that.

Doing an ASCII conversion fixed my problem.

`x509 = X509.load_cert_string(cert_unicode_suspect.encode('ascii', 'ignore'))`

I believe it would be safe to ignore Unicode to ASCII conversion issues, since PEM format is defined in ASCII encoding anyways.

I'd like to work on a patch to do a type check for the `load_cert_string function`, so that we can handle developers' various scenarios a bit more gracefully.

**Comment by mcepl** [comment]
Please, file a ticket at https://github.com/martinpaljak/M2Crypto/issues. This repo is now dead and unmaintained.
